# commit to be tagged for new release
commit = "HEAD"

project_name = "containerd"
github_repo = "containerd/containerd"
match_deps = "^github.com/(containerd/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.6.10"

pre_release = false

preface = """\
The eleventh patch release for containerd 1.6 contains a various fixes and updates.

### Notable Updates
* **Add pod UID annotation in CRI plugin** ([#7735](https://github.com/containerd/containerd/pull/7735))
* **Fix nil pointer deference for Windows containers in CRI plugin** ([#7737](https://github.com/containerd/containerd/pull/7737))
* **Fix lease labels unexpectedly overwriting expiration** ([#7745](https://github.com/containerd/containerd/pull/7745))
* **Fix for simultaneous diff creation using the same parent snapshot** ([#7756](https://github.com/containerd/containerd/pull/7756))

See the changelog for complete list of changes"""
